"use client";
import { Area, Bar, CartesianGrid, ComposedChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { Dispatch } from "@/types/api";

export function DispatchChart({rows}:{rows:Dispatch[]}){
 const data=rows.map(r=>({...r,time:r.timestamp_local.slice(11,16),charge:r.power_mw<0?r.power_mw:0,discharge:r.power_mw>0?r.power_mw:0}));
 const charges=rows.filter(r=>r.action==="charge"),discharges=rows.filter(r=>r.action==="discharge");
 const low=Math.min(...rows.map(r=>r.price_eur_mwh)),high=Math.max(...rows.map(r=>r.price_eur_mwh));
 const summary="The battery charges in "+charges.length+" low-price intervals and discharges in "+discharges.length+" high-price intervals.";
 return <figure className="dispatch-figure">
  <div className="chart-overview"><div><span className="chart-kicker">OPTIMIZATION RESULT</span><h3>Day-Ahead Dispatch</h3><p>{summary}</p></div><div className="chart-facts"><span><small>Lowest forecast</small><strong>{euro(low)}/MWh</strong></span><span><small>Highest forecast</small><strong>{euro(high)}/MWh</strong></span><span><small>Spread</small><strong>{euro(high-low)}/MWh</strong></span></div></div>
  <div className="plot-card price-plot"><div className="plot-heading"><span><i className="legend-line price"/>Forecast Price</span><strong>€/MWh</strong></div><div className="plot-area" role="img" aria-label={"Day-Ahead price forecast in euros per megawatt-hour. "+summary}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} syncId="dispatch" margin={{top:8,right:18,bottom:0,left:4}}><defs><linearGradient id="priceFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#1d5963" stopOpacity=".18"/><stop offset="100%" stopColor="#1d5963" stopOpacity=".02"/></linearGradient></defs><CartesianGrid stroke="#dce5e3" strokeDasharray="3 3" vertical/><XAxis dataKey="time" hide/><YAxis width={55} tick={{fontSize:11,fill:"#607477"}} axisLine={false} tickLine={false} tickFormatter={v=>"€"+v}/><Tooltip content={<Tip/>}/><Area dataKey="price_eur_mwh" name="Forecast price" stroke="#174b56" fill="url(#priceFill)" strokeWidth={2.5} dot={false}/></ComposedChart></ResponsiveContainer></div></div>
  <div className="plot-card dispatch-plot"><div className="plot-heading"><span><i className="legend-block charge"/>Charge <b>−</b><i className="legend-block discharge"/>Discharge <b>+</b><i className="legend-line soc"/>State of Charge</span><span className="axis-units"><strong>MW</strong><strong>MWh</strong></span></div><div className="plot-area large" role="img" aria-label={"Battery dispatch in megawatts and state of charge in megawatt-hours. "+summary}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} syncId="dispatch" margin={{top:9,right:10,bottom:2,left:4}}><defs><linearGradient id="socFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#655fb4" stopOpacity=".18"/><stop offset="100%" stopColor="#655fb4" stopOpacity=".02"/></linearGradient></defs><CartesianGrid stroke="#dce5e3" strokeDasharray="3 3" vertical/><XAxis dataKey="time" interval={Math.max(Math.floor(rows.length/8),0)} tick={{fontSize:11,fill:"#607477"}} axisLine={{stroke:"#aebfbc"}} tickLine={false} height={34}/><YAxis yAxisId="power" width={55} domain={[-55,55]} ticks={[-50,-25,0,25,50]} tick={{fontSize:11,fill:"#607477"}} axisLine={false} tickLine={false} tickFormatter={v=>v+" MW"}/><YAxis yAxisId="soc" orientation="right" width={58} domain={[0,100]} ticks={[0,25,50,75,100]} tick={{fontSize:11,fill:"#655fb4"}} axisLine={false} tickLine={false} tickFormatter={v=>v+" MWh"}/><Tooltip content={<Tip/>}/><ReferenceLine yAxisId="power" y={0} stroke="#81928f" strokeWidth={1.2}/><ReferenceLine yAxisId="soc" y={10} stroke="#a7a2d5" strokeDasharray="5 4"/><ReferenceLine yAxisId="soc" y={90} stroke="#a7a2d5" strokeDasharray="5 4"/><Bar yAxisId="power" dataKey="charge" name="Charge MW" fill="#1d9c98" radius={[3,3,0,0]} maxBarSize={18}/><Bar yAxisId="power" dataKey="discharge" name="Discharge MW" fill="#e67d11" radius={[3,3,0,0]} maxBarSize={18}/><Area yAxisId="soc" dataKey="soc_mwh" name="SoC MWh" stroke="#655fb4" fill="url(#socFill)" strokeWidth={2.5} type="stepAfter" dot={false}/></ComposedChart></ResponsiveContainer></div></div>
  <div className="chart-foot"><span><i className="bound"/>Dashed lines: configured 10–90 MWh SoC envelope</span><span>Delivery time · Europe/Zurich · hover for exact values</span></div>
  <details className="data-table-toggle"><summary>View Accessible Interval Table</summary><div className="table-scroll"><table><thead><tr><th>Delivery Time</th><th>Forecast Price</th><th>Action</th><th>Power</th><th>SoC</th><th>Contribution</th></tr></thead><tbody>{data.map(r=><tr key={r.interval}><td>{r.time}</td><td>{euro(r.price_eur_mwh)}/MWh</td><td>{title(r.action)}</td><td>{r.power_mw.toFixed(1)} MW</td><td>{r.soc_mwh.toFixed(1)} MWh</td><td>{euro(r.interval_pnl_eur)}</td></tr>)}</tbody></table></div></details>
 </figure>;
}
function Tip({active,payload,label}:{active?:boolean;payload?:Array<{payload:Dispatch}>;label?:string}){if(!active||!payload?.[0])return null;const r=payload[0].payload;return <div className="chart-tip"><span className="tip-time">{label} · Europe/Zurich</span><strong>{title(r.action)} {Math.abs(r.power_mw).toFixed(1)} MW</strong><dl><div><dt>Forecast price</dt><dd>{euro(r.price_eur_mwh)}/MWh</dd></div><div><dt>State of charge</dt><dd>{r.soc_mwh.toFixed(1)} MWh</dd></div><div><dt>Interval contribution</dt><dd>{euro(r.interval_pnl_eur)}</dd></div></dl></div>;}
const euro=(v:number)=>new Intl.NumberFormat("en-CH",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(v);
const title=(v:string)=>v.charAt(0).toUpperCase()+v.slice(1);
