import type { Market, Order } from "@/types/api";
export function OrderTable({orders,market,selectedId,onSelect}:{orders:Order[];market:Market;selectedId?:string;onSelect?:(order:Order)=>void}){
 if(!orders.length)return <div className="state-block"><strong>No orders in this proposal</strong><span>The optimal decision may be to remain idle under the current assumptions.</span></div>;
 return <div className="table-scroll order-table"><table><caption className="sr-only">Generated Day-Ahead order proposal</caption><thead><tr><th scope="col">Delivery</th><th scope="col">Side</th><th scope="col" className="numeric">MW</th><th scope="col" className="numeric">MWh</th><th scope="col" className="numeric">Limit {market.currency}/MWh</th><th scope="col" className="numeric">Interval contribution</th><th scope="col">Confidence</th><th scope="col">Status</th></tr></thead><tbody>{orders.map(o=><tr key={o.order_id} className={selectedId===o.order_id?"selected":""}><td><button className="row-select" onClick={()=>onSelect?.(o)} aria-label={"Edit "+o.side+" order at "+o.delivery_start_utc}><strong>{formatTime(o.delivery_start_utc,market.timezone)}</strong><small>{formatDate(o.delivery_start_utc,market.timezone)} · {o.product}</small></button></td><td><span className={"side "+o.side.toLowerCase()}>{o.side}</span></td><td className="numeric">{n(o.volume_mw,1)}</td><td className="numeric">{n(o.energy_mwh,2)}</td><td className="numeric">{n(o.limit_price_eur_mwh,2)}</td><td className={"numeric "+(o.expected_contribution_eur>=0?"positive":"negative")}>{money(o.expected_contribution_eur,market.currency)}</td><td>{o.confidence}</td><td><span className="status-tag">{title(o.status)}</span></td></tr>)}</tbody></table></div>;
}
const n=(v:number,d:number)=>new Intl.NumberFormat("en-CH",{minimumFractionDigits:d,maximumFractionDigits:d}).format(v);
const money=(v:number,currency:string)=>new Intl.NumberFormat("en-CH",{style:"currency",currency,maximumFractionDigits:0}).format(v);
const title=(v:string)=>v.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
function formatTime(v:string,timeZone:string){return new Intl.DateTimeFormat("en-CH",{hour:"2-digit",minute:"2-digit",timeZone,timeZoneName:"short"}).format(new Date(v));}
function formatDate(v:string,timeZone:string){return new Intl.DateTimeFormat("en-CH",{day:"2-digit",month:"short",timeZone}).format(new Date(v));}
