import type { Order } from "@/types/api";
export function OrderTable({orders,selectedId,onSelect}:{orders:Order[];selectedId?:string;onSelect?:(order:Order)=>void}){
 if(!orders.length)return <div className="state-block"><strong>No orders in this proposal</strong><span>The optimal decision may be to remain idle under the current assumptions.</span></div>;
 return <div className="table-scroll order-table"><table><caption className="sr-only">Generated Day-Ahead order proposal</caption><thead><tr><th scope="col">Delivery</th><th scope="col">Side</th><th scope="col" className="numeric">MW</th><th scope="col" className="numeric">MWh</th><th scope="col" className="numeric">Limit €/MWh</th><th scope="col" className="numeric">Interval contribution</th><th scope="col">Confidence</th><th scope="col">Status</th></tr></thead><tbody>{orders.map(o=><tr key={o.order_id} className={selectedId===o.order_id?"selected":""}><td><button className="row-select" onClick={()=>onSelect?.(o)} aria-label={"Edit "+o.side+" order at "+o.delivery_local}><strong>{formatTime(o.delivery_local)}</strong><small>{formatDate(o.delivery_local)} · {o.product}</small></button></td><td><span className={"side "+o.side.toLowerCase()}>{o.side}</span></td><td className="numeric">{n(o.volume_mw,1)}</td><td className="numeric">{n(o.energy_mwh,2)}</td><td className="numeric">{n(o.limit_price_eur_mwh,2)}</td><td className={"numeric "+(o.expected_contribution_eur>=0?"positive":"negative")}>{money(o.expected_contribution_eur)}</td><td>{o.confidence}</td><td><span className="status-tag">{title(o.status)}</span></td></tr>)}</tbody></table></div>;
}
const n=(v:number,d:number)=>new Intl.NumberFormat("en-CH",{minimumFractionDigits:d,maximumFractionDigits:d}).format(v);
const money=(v:number)=>new Intl.NumberFormat("en-CH",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(v);
const title=(v:string)=>v.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
function formatTime(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("en-CH",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Zurich",timeZoneName:"short"}).format(d);}
function formatDate(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?"":new Intl.DateTimeFormat("en-CH",{day:"2-digit",month:"short",timeZone:"Europe/Zurich"}).format(d);}
