/** optimization API contracts. Values here are validated by the backend, not by TypeScript. */
import type { Order } from "./orders";
import type { AuditMetadata, Battery, Dispatch, Market, ValidationStatus } from "./shared";
export type SimulationSummary = {
  expected_contribution_eur: number;
  optimized_contribution_eur: number;
  baseline_proposal_contribution_eur: number;
  proposal_contribution_eur: number;
  proposal_terminal_soc_mwh: number;
  proposal_throughput_mwh: number;
  proposal_equivalent_cycles: number;
  proposal_min_soc_mwh: number;
  proposal_max_soc_mwh: number;
  proposal_sales_revenue_eur: number;
  proposal_purchase_cost_eur: number;
  proposal_degradation_cost_eur: number;
  proposal_transaction_fee_eur: number;
  proposal_buy_volume_mwh: number;
  proposal_sell_volume_mwh: number;
  trader_adjustment_delta_eur: number;
  sales_revenue_eur: number;
  purchase_cost_eur: number;
  degradation_cost_eur: number;
  transaction_fee_eur: number;
  charged_grid_mwh: number;
  discharged_grid_mwh: number;
  throughput_mwh: number;
  equivalent_cycles: number;
  min_soc_mwh: number;
  max_soc_mwh: number;
  order_count: number;
  buy_volume_mwh: number;
  sell_volume_mwh: number;
  executable_rounding_delta_eur: number;
  terminal_energy_value_eur: number;
  total_decision_value_eur: number;
};
export type RiskSummary = {
  posture: string;
  expected_contribution_eur: number;
  downside_contribution_eur: number;
  upside_contribution_eur: number;
  worst_case_contribution_eur: number;
  value_range_eur: number;
  recommended_scenario: string;
  recommendation: string;
  outcomes: { name: string; probability: number; contribution_eur: number }[];
};
export type SimulationRunSummary = {
  simulation_id: string;
  created_at_utc: string;
  display_name: string;
  delivery_date: string;
  scenario_name: string;
  product_minutes: 15 | 60;
  risk_posture: string;
  horizon_policy: string;
  capacity_mwh: number;
  validation_status: string;
  modified_by_trader: boolean;
  expected_contribution_eur: number;
  downside_contribution_eur?: number;
  upside_contribution_eur?: number;
  throughput_mwh: number;
  equivalent_cycles: number;
  order_count: number;
  input_hash: string;
};
export type ComparisonMetric = "contribution" | "throughput" | "cycles" | "orders";
export type SensitivityCase = {
  value: number;
  unit: string;
  contribution_eur: number;
  delta_eur: number;
  feasible: boolean;
  bounded?: boolean;
  explanation: string;
};
export type SensitivityItem = {
  key: string;
  label: string;
  baseline_value: number;
  tested_value: number;
  unit: string;
  contribution_delta_eur: number;
  marginal_value_eur: number;
  interpretation: string;
  category?: "operational" | "strategy";
  default_selected?: boolean;
  lower_case?: SensitivityCase | null;
  upper_case?: SensitivityCase | null;
  calculation?: "full_reoptimization";
};
export type Simulation = {
  simulation_id: string;
  display_name?: string;
  created_at_utc: string;
  delivery_date: string;
  scenario_name: string;
  strategy?: "expected_value" | "conservative";
  risk_posture?: "expected_value" | "balanced" | "downside_protected";
  horizon_policy?: "minimum_reserve" | "terminal_value" | "next_day_proxy" | "multi_day";
  terminal_value_eur_per_mwh?: number;
  price_multiplier?: number;
  peak_reduction_eur_mwh?: number;
  scenario_probabilities?: { downside: number; expected: number; upside: number };
  lookahead_hours?: number;
  proposal_revision?: number;
  data_mode: string;
  submission_mode: string;
  battery: Battery;
  market: Market;
  dispatch: Dispatch[];
  orders: Order[];
  validation: {
    status: ValidationStatus;
    findings: {
      severity: string;
      code: string;
      message: string;
      interval?: number;
      observed_value?: number;
      configured_limit?: number;
      difference?: number;
      tolerance?: number;
      unit?: string;
      source?: string;
    }[];
  };
  summary: SimulationSummary;
  optimization: {
    engine: string;
    prototype_solver: boolean;
    solver_status?: string;
    solve_time_ms?: number;
    mip_gap?: number;
    objective: string;
    objective_value_eur: number;
    terminal_soc_mwh: number;
    constraint_status: string;
    constraints: string[];
  };
  proposal?: {
    proposal_contribution_eur: number;
    proposal_terminal_soc_mwh: number;
    proposal_throughput_mwh: number;
    proposal_equivalent_cycles: number;
    proposal_min_soc_mwh: number;
    proposal_max_soc_mwh: number;
    proposal_sales_revenue_eur: number;
    proposal_purchase_cost_eur: number;
    proposal_degradation_cost_eur: number;
    proposal_buy_volume_mwh: number;
    proposal_sell_volume_mwh: number;
    implied_soc_mwh: number[];
    implied_dispatch?: Dispatch[];
  };
  audit: AuditMetadata;
  approval_status?: string;
  order_generation?: {
    method: string;
    volume_increment_mw: number;
    adjusted_order_count: number;
    repaired_order_count: number;
    volume_reduction_mwh: number;
    contribution_delta_eur: number;
    validation_status: string;
  };
  risk?: RiskSummary;
  horizon?: {
    policy: string;
    terminal_value_eur_per_mwh: number;
    reserve_soc_mwh: number;
    terminal_soc_mwh: number;
    incremental_stored_energy_mwh: number;
    terminal_energy_value_eur: number;
  };
  forecast?: {
    source_type: "illustrative" | "manual" | "file";
    source_name: string;
    version: string;
    created_at_utc?: string;
    bidding_zone: string;
  };
  forecast_points?: { timestamp_utc: string; timestamp_local: string; price_eur_mwh: number }[];
  sensitivities?: SensitivityItem[];
};
